name: fluttermuvis
description: A port of my Kotlin side-project Muvis.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  # HTTP library (https://pub.dartlang.org/packages/http)
  http: 0.11.3+16
  # Flutter library to show a staggered grid (https://github.com/letsar/flutter_staggered_grid_view)
  flutter_staggered_grid_view: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/bg_splash.png
   - assets/ic_detail_rating.png
   - assets/ic_empty_favorite.png
   - assets/ic_empty_films.png
   - assets/ic_empty_search.png
   - assets/ic_fab_fav.png
   - assets/ic_fab_unfav.png
   - assets/ic_favorites.png
   - assets/ic_filter.png
   - assets/ic_movie_rating.png
   - assets/ic_movies.png
   - assets/ic_search.png
   - assets/img_play_button.png
   - assets/search.png
   - assets/splash_logo.png
   - assets/toolbar_logo.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
